### ISSUE TITLE
exposing non-dimmable light (incorrectly) as dimmable?

### ISSUE THREAD

**Issue by clementx2006** [rzulian/lutron_custom_component#2]
Hello! thanks again for making this fork - has helped a lot and saved a lot of time for a lot of us :-) 

Question (and perhaps I am doing something wrong): it would seem that all the non-dimmable lights are exposed as dimmable in Home Assistant? I have some loads in Lutron specified as 'NON_DIM*' and they all seem to get brightness sliders in the HA. If this was the design, the small concern - small as most modern lights would have some form of protection - would that it could damage certain light fixtures in the operation. 

Shout if you think I am doing something wrong!

**Comment by rzulian** [comment]
@clementx2006 let me check this

**Comment by rzulian** [comment]
You are right! fixed in 1aee01d
