### ISSUE TITLE
led state

### ISSUE THREAD

**Issue by wiwan-wijoyo** [rzulian/lutron_custom_component#3]
how to create led states?
can you show me an example?

**Comment by rzulian** [comment]
leds are created as lights, so you can simply check the state 
the name is  light.<zone>_keypad_<number>_led_<position>

you can switch on/off a led

`
switches:
      door:
        friendly_name: "door"
        turn_on:
          - service: light.turn_on
            entity_id: light.entrance_keypad_1_led_7
`


currently, I'm creating a led only if the associated button is controlled via automation
https://github.com/rzulian/lutron_custom_component/blob/1aee01d4a7366dc50a21c5f352ea9d7a16be9984/__init__.py#L102

Do you have a different use case?

**Comment by wiwan-wijoyo** [comment]
light (led keypad) not appear in entities, only scene appear.

Name                                          Entity ID                                                Integration
Living Room keypad 19: Btn 6   scene.living_room_keypad_19_btn_6     Scene

**Comment by rzulian** [comment]
you probably don't have integrations associated with the buttons in the Lutron project.
you can try to modify the line 102 with: ` if not(led is None):`
this will create a led for every button.
I could make this an option in the configuration

**Comment by wiwan-wijoyo** [comment]
line 102 I modify remove the (led is None) :" if not button.led_logic==5:"  now can works well. the light (led keypad) appear in entity.
thanks alot...

how to query state led keypad? for example if press button manual keypad then light.keypadled status on. 
now no effect if press manual keypad.

lutron command test with terminal telnet.
ID keypad : 19
ID led button 1 : 86
query status command: 
?DEVICE,19,86,9
result : 
~DEVICE,19,86,9,0 = led status keypad button 1 off
~DEVICE,19,86,9,1 = led status keypad button 1 on
