### ISSUE TITLE
db_file not supported and version key for manifest.json needed

### ISSUE THREAD

**Issue by txwindsurfer** [rzulian/lutron_custom_component#4]
@rzulian  I was just checking to see if you planned to continue to support your custom_component.  I have been using it on a test machine for a long time and it works great with my Homeworks QS.  I am able to see and control my keypads which I could not do with the standard Lutron integraton in HA. I was thinking about migrating it to my production environment.

I just updated Home  Assistant to 2021.10.0.dev20210902 after waiting many months and a couple of things didn't work.  The db_file configuration entry is seen as an error and the manifest.json need a version key (see https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions).  

I changed line 32 adding the name of my db_file in __init__.py:
                vol.Optional(CONF_LUTRON_DB_FILE, default='Lutron.xml'): cv.string,
I changed manifest.json adding:
  "version": "1.0.0"
to the end with a , on the previous line.

All works with those two changes

**Comment by rzulian** [comment]
hey!
I'm supporting this component, also because I'm using it in production ;)
I'm trying to understand which is the best practice to maintain it. I've this repo, but I can only test it in a test envinronment, and use the component in production. But I'm not sure how I can manage those copies.
